### ISSUE TITLE
Submit paysimple-ruby 0.2.1 to rubygems

### ISSUE THREAD

**Issue by nrowegt** [koss-lebedev/paysimple-ruby#3]
Rubygems doesn't have 0.2.1 submitted, which fixes a few issues with 0.2.0. From bundle install with 0.2.1 specified:
`Could not find gem 'paysimple-ruby (~> 0.2.1)' in any of the gem sources listed in your Gemfile or available on this machine.`

**Comment by koss-lebedev** [comment]
Thanks for pointing this out, I just pushed v0.2.1 to RubyGems
